name: Deploy Staging

on:
  push:
    branches: [ staging ]

jobs:
  distribute-android:
    runs-on: ubuntu-latest
    steps:
      # Node
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: YARN Cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: YARN Install
        run: |
          echo "${{ secrets.ENV }}" > .env
          sed -i -e 's/ && cd ios && pod install && cd ..//g' package.json
          yarn install

      # Build
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install firebase tool
        run: |
          yarn global add firebase-tools
      - name: Bundle Cache
        uses: actions/cache@v2
        with:
          path: android/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup fastlane
        run: |
          echo "${{ secrets.FASTLANE_ANDROID_ENV }}" > android/fastlane/.env
          cd android && bundle install
      - name: Distribute to firebase
        run: cd android && bundle exec fastlane staging

  distribute-ios:
    runs-on: macOS-latest
    steps:
      # Node
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: YARN Cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Pods Cache
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: YARN Install
        run: |
          echo "${{ secrets.ENV }}" > .env
          yarn install

      # Build
      - name: Setup fastlane
        run: |
          echo "${{ secrets.FASTLANE_IOS_ENV }}" > ios/fastlane/.env
      - name: Distribute to firebase
        run: cd ios && fastlane staging
